apiVersion: 1

contactPoints:
  - orgId: 1
    name: grafana-default-email
    receivers:
      - uid: grafana-default-email
        type: email
        settings:
          addresses: team@brain-tumor-mlops.local
          singleEmail: false

notificationPolicies:
  - orgId: 1
    receiver: grafana-default-email
    group_by: ["alertname"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: grafana-default-email
        matchers:
          - severity = critical
        group_wait: 10s
      - receiver: grafana-default-email
        matchers:
          - severity = warning
